[tools]
node = "22.18.0"
python = "3.11.0"
java = "temurin-8"
maven = "3.9.9"

[env]
# 设置镜像源
PYPI_MIRROR = 'https://pypi.tuna.tsinghua.edu.cn/simple'
NPM_REGISTRY = 'https://registry.npmmirror.com'

[settings]
use_versions_host = true        # 避免GitHub API限制